### ISSUE TITLE
should we keep the private EEIA2022_Private repo ?

### ISSUE THREAD

**Issue by rleriche** [rleriche/Optimization_AI_Cotonou_2022#14]
EEIA2022_Private was open to have a space to continue to work on this project without public visibility. It is a pain to have parallel versions of the same files. But may be in the future we will keep adding to it. 
Should we delete EEIA2022_Private ?

**Comment by BWhannou** [comment]
I would suggest to delete the private version, because they are doing exactly the same thing. Now we've shared the correction file with the students, I don't see why we should have a private repo. We can continue to work on the project with a different branch (it won't be private, though)
@akouete-kpakpo @rleriche

**Comment by akouete-kpakpo** [comment]
@rleriche @BWhannou ok with your comments. 

We should delete `EEIA2022_Private` to minimize cost of maintenance.

**Comment by rleriche** [comment]
Ok, `EEIA2022_Private` is deleted.
